[package]
name = "rayst"
version = "0.1.0"
edition = "2021"
authors = ["wolfi"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"